title: Tabulexa
description: Digital handwriting app for presentations and teaching
google_analytics: UA-173535926-3
theme: jekyll-theme-minimal
bing_site_verification: "6D43BC2018CF39D0C19A30747582236D"
